# Generated by Django 5.0.4 on 2024-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_slug_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.CharField(max_length=300),
        ),
    ]
